[package]
name = "compounderr"
version = "0.1.1"
edition = "2021"

[dependencies]
composerr = { git = "https://github.com/nain-F49FF806/composerr.git", version = "0.2.6" }
thiserror = { version = "2.0.3", features = ["std"] }

[dev-dependencies]
rand = "0.8.5"
